/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registermini;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author MAHE
 */
public class LoginKaro extends javax.swing.JFrame {

    /**
     * Creates new form LoginKaro
     */
    public LoginKaro() {
    	setTitle("LoginFrame");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lgpanel1 = new javax.swing.JPanel();
        lglabel1 = new javax.swing.JLabel();
        lgpanel2 = new javax.swing.JPanel();
        lglabel2 = new javax.swing.JLabel();
        lglabel3 = new javax.swing.JLabel();
        lgtextfield1 = new javax.swing.JTextField();
        lglabel4 = new javax.swing.JLabel();
        lgbutton1 = new javax.swing.JButton();
        lglabel5 = new javax.swing.JLabel();
        lgbutton2 = new javax.swing.JButton();
        lgpasswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lgpanel1.setBackground(new java.awt.Color(248, 148, 6));

        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Shopify_logo_small.png"))); // NOI18N

        javax.swing.GroupLayout gl_lgpanel1 = new javax.swing.GroupLayout(lgpanel1);
        lgpanel1.setLayout(gl_lgpanel1);
        gl_lgpanel1.setHorizontalGroup(
            gl_lgpanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_lgpanel1.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lglabel1)
                .addGap(113, 113, 113))
        );
        gl_lgpanel1.setVerticalGroup(
            gl_lgpanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_lgpanel1.createSequentialGroup()
                .addContainerGap()
                .addComponent(lglabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lgpanel2.setBackground(new java.awt.Color(44, 62, 80));

        lglabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lglabel2.setForeground(new java.awt.Color(240, 240, 240));
        lglabel2.setText("LOGIN");

        lglabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lglabel3.setForeground(new java.awt.Color(240, 240, 240));
        lglabel3.setText("USERNAME");

        lglabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lglabel4.setForeground(new java.awt.Color(240, 240, 240));
        lglabel4.setText("PASSWORD");

        lgbutton1.setText("LOGIN");
        lgbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lglabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lglabel5.setForeground(new java.awt.Color(240, 240, 240));
        lglabel5.setText("DONT HAVE AN ACCOUNT??");

        lgbutton2.setText("REGISTER NOW!");
        lgbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_lgpanel2 = new javax.swing.GroupLayout(lgpanel2);
        lgpanel2.setLayout(gl_lgpanel2);
        gl_lgpanel2.setHorizontalGroup(
            gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_lgpanel2.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_lgpanel2.createSequentialGroup()
                        .addComponent(lglabel2)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_lgpanel2.createSequentialGroup()
                        .addComponent(lgbutton1)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_lgpanel2.createSequentialGroup()
                        .addComponent(lgbutton2)
                        .addGap(142, 142, 142))))
            .addGroup(gl_lgpanel2.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lglabel5)
                    .addGroup(gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(gl_lgpanel2.createSequentialGroup()
                            .addComponent(lglabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lgpasswd))
                        .addGroup(gl_lgpanel2.createSequentialGroup()
                            .addComponent(lglabel3)
                            .addGap(18, 18, 18)
                            .addComponent(lgtextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        gl_lgpanel2.setVerticalGroup(
            gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_lgpanel2.createSequentialGroup()
                .addContainerGap()
                .addComponent(lglabel2)
                .addGap(36, 36, 36)
                .addGroup(gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lglabel3)
                    .addComponent(lgtextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gl_lgpanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lglabel4)
                    .addComponent(lgpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lgbutton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lglabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgbutton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lgpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lgpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        Registerkaro rkf = new Registerkaro();
        rkf.setVisible(true);
        rkf.pack();
        rkf.setLocationRelativeTo(null);
        //rkf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        Shopping skp = new Shopping();
        skp.setVisible(true);
        skp.pack();
        skp.setLocationRelativeTo(null);
        //rkf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginKaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginKaro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton lgbutton1;
    private javax.swing.JButton lgbutton2;
    private javax.swing.JLabel lglabel1;
    private javax.swing.JLabel lglabel2;
    private javax.swing.JLabel lglabel3;
    private javax.swing.JLabel lglabel4;
    private javax.swing.JLabel lglabel5;
    private javax.swing.JPanel lgpanel1;
    private javax.swing.JPanel lgpanel2;
    private javax.swing.JPasswordField lgpasswd;
    private javax.swing.JTextField lgtextfield1;
    // End of variables declaration                   
}