/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registermini;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author MAHE
 */
public class Shopping extends javax.swing.JFrame {

    /**
     * Creates new form Shopping
     */
    public Shopping() {
    	setTitle("Shopframe");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        shppanel1 = new javax.swing.JPanel();
        shplabel1 = new javax.swing.JLabel();
        shplabel1.setBounds(246, 12, 0, 0);
        shppanel2 = new javax.swing.JPanel();
        shplabel2 = new javax.swing.JLabel();
        shplabel2.setBounds(193, 0, 386, 43);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shppanel1.setBackground(new java.awt.Color(248, 148, 6));

        shppanel2.setBackground(new java.awt.Color(44, 62, 80));

        shplabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        shplabel2.setForeground(new java.awt.Color(240, 240, 240));
        shplabel2.setText("SHOPPING PORTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(shppanel1, GroupLayout.PREFERRED_SIZE, 772, Short.MAX_VALUE)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(12)
        			.addComponent(shppanel2, GroupLayout.PREFERRED_SIZE, 760, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(shppanel1, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(shppanel2, GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        			.addContainerGap())
        );
        shppanel2.setLayout(null);
        shppanel2.add(shplabel2);
        getContentPane().setLayout(layout);
        shppanel1.setLayout(null);
        shppanel1.add(shplabel1);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shopping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel shplabel1;
    private javax.swing.JLabel shplabel2;
    private javax.swing.JPanel shppanel1;
    private javax.swing.JPanel shppanel2;
    // End of variables declaration                   
}